### ISSUE TITLE
Belt tensioning is overly complicated

### ISSUE THREAD

**Issue by nevernormal1** [inventables/x-carve-instructions#1]
The order of operations for explaining how to tension the belts is overly-complicated. It requires you to exert an unnecessary amount of effort and may require you to undo all of that work to feed more belt through the belt clip.

You're tightening the fixed side first then you have to properly feed the right amount of belt so that you end up close enough to the end plate so that the tensioning step can make it tight.

A better way would be to attach the belt tensioning screw just enough so that it's on there, then make the fixed end tight, then do the tensioning.

**Comment by Geterdoneright** [comment]
The present instructions are fine, in my opinion if they included this thought for the belt installations:  If you use a cable tie strap on each belt at both ends, just before the beginning of each end plate, you won't have to redo/undue your work if you --->  Make sure the knot on the end of each strap is on the bottom side of the belt so it can be tucked into the slot between the two rails.  You have to use straps of the correct size, a snug fit ( I used a type from www.bulldoghardware.com, cable tie size indicated on pkg. is 7-7/8 (20 cm), push it into the slot with a screwdriver.  I can now tighten mine so tight that if the screw was long enough the belt would snap. This is a closed issue with me, it was frustrating how I had to find this out, you can't imagine how many times I had to redo the steps, each time with a new method.  I'd pause for awhile and rethink.  I just finished it today, I don't know a thing about CNC machines, looking forward to the challenge. Don't know where to start,  Autodesk Fusion 360 looks like a monster.  I"m lost and I can't get up!

**Comment by mstych** [comment]
@Geterdoneright - Thank you for contributing these feedback. We know it is not a simple thing to get belts properly tensioned, and we are working on some improvements for this process on our new machine. The [video for tuning and calibration](http://x-carve-instructions.inventables.com/step15/) helps, but we know it isn't straight-forward. Your feedback is definitely appreciated, as we are always trying to make things easier for our customers. If you would like any assistance with your machine or getting things up and running, please [feel free to contact us](https://inventables.desk.com/customer/portal/emails/new) or [touch base on our forum](https://discuss.inventables.com/). We're happy to help!
