### ISSUE TITLE
More Detail required in Drag Chain sections

### ISSUE THREAD

**Issue by johndudleyhayes** [inventables/x-carve-instructions#115]
Address the following feedback:

> You have detailed instructions on how to attach the Z-Probe wire to the X-Carriage but then don't describe if the wire should go in the drag chain with the rest of the wires. And speaking of the Drag chain the documentation says place the "spindle cord" in the drag chain. I couldn't figure out if you meant "spindle power cord" or some other cord that I didn't know about. It took me a while to figure out that the drag chain end brackets you show in a picture are actually attached to the drag chain and can be removed.

**Comment by johnlafon** [comment]
Also, in that section where it says "Attach the drag chain end to the drag chain bracket on the x-carriage." it does't specify what screw length to use.  I assumed M5x12 Flat Head with M5 Nylon Lock Nut.
