### ISSUE TITLE
Trouble seating the gShield onto the Arduino

### ISSUE THREAD

**Issue by paulkaplan** [inventables/x-carve-instructions#12]
Many people including Jeff and Chris (and Jeff says at least 10 others from the forum) have an issue seating the gShield on the Arduino after the Arduino has been mounted to the enclosure. 

We should put special notes in the instructions, troubleshooting in the forum, etc. We might need a design change also.

**Comment by vaporlock** [comment]
If the slots were opened down a bit more we would be able to see the pins as they engage. That's the problem as I see it (or can't see it :) )
