### ISSUE TITLE
Drag Chain End

### ISSUE THREAD

**Issue by johndudleyhayes** [inventables/x-carve-instructions#159]
Add instruction to remove drag chain end from the length of drag chain in the wiring step:

http://x-carve-instructions.inventables.com/1000mm/step6/

**Comment by giovannadf** [comment]
Customer Feedback on same step:
> Locate the end of the drag chain, two M5 10mm flat head cap screws,
> and two post-assembly insertion nuts. Add the post-assembly insertion
> nuts into the extrusion located behind the wide MakerSlide.

Its not clear that the end of the Drag Chain (the bracket) is not in a zip-lock
envelope, but attached to the Drag Chain itself, and needs to be removed.

> Mount the drag chain end to the extrusion by installing the flat head
> cap screws into the post-assembly insertion nuts.

The next picture shows the two post-assembly insertion nuts, but there is no
location information. Possibly you should include a measurement from the side
rail?
