### ISSUE TITLE
Customer feedback - Zip tie mounts

### ISSUE THREAD

**Issue by giovannadf** [inventables/x-carve-instructions#163]
> Use three zip tie mounts on the top of the aluminum extrusion.

The picture shows two, and its black on black so very difficult to see. Maybe explain
that one goes 2” from the exit of the Drag Chain, one goes 2” from the left end of the
extrusion, and one goes in between the other two.

(I would recommend arrows or editing to highlight position.)

**Comment by JulieInventables** [comment]
Include using hex wrench to put those on the drag chain extrusion
