### ISSUE TITLE
Icons are too large for the slide out menu

### ISSUE THREAD

**Issue by paulkaplan** [inventables/x-carve-instructions#19]
Hamburger and the "x" out of the sidebar are huge.

![screen shot 2015-06-05 at 4 01 08 pm](https://cloud.githubusercontent.com/assets/654102/8015206/360e9434-0b9c-11e5-8c11-882e2a9cc83a.png)

![screen shot 2015-06-05 at 4 01 14 pm](https://cloud.githubusercontent.com/assets/654102/8015207/38dfdb0a-0b9c-11e5-8e5d-7d120164bc0e.png)

**Comment by chrisbalin** [comment]
Fixed.

![screen shot 2015-06-08 at 10 32 33 am](https://cloud.githubusercontent.com/assets/4512685/8038550/ccc43d0a-0dc9-11e5-8b24-7ab99ed43637.png)

![screen shot 2015-06-08 at 10 32 27 am](https://cloud.githubusercontent.com/assets/4512685/8038554/d0d82c1c-0dc9-11e5-8e2a-323a7df0c2e9.png)
