### ISSUE TITLE
Orientation of makerslide slots for limit switch actuators is unclear

### ISSUE THREAD

**Issue by nevernormal1** [inventables/x-carve-instructions#2]
If you are using limit switches, the orientation of your makerslide rails is important because you'll put a screw into one of the slots at the end of assembly that becomes the actuator for the switch (it is what the switch bumps into to engage). Makerslide is not completely symmetrical. One side has 2 slots and the other side only has one and it is not in the center. It is possible to assemble it with this slot on the "top" or the "bottom." The instructions for attaching the limit switches assume you'll be assembling the rails with slot in the "top" position but this is not shown in the video and there is only a blurb about it without a clear picture or explanation in the written part of the instructions. Several people have done it backwards and posted about it on the forum. There is a fix, but it's annoying to have to go back and undo something you already did when it could just be explained at the beginning.

**Comment by paulkaplan** [comment]
@johndudleyhayes is this still true?

**Comment by roguenroll** [comment]
Yes still true in October. I wish this was corrected. > same as he said above.

That slot orientation should be addressed, whether its top or bottom, make that understood, then have us attach the limiter for whatever orientation that it is. I have to turn over the switches.

Also it mentions the insertions nuts for the pullies (not at this point yet), but I have the rails done and I didnt see the insertions nut for those limiter switches.

**Comment by roguenroll** [comment]
just double checked.

Info:
model has bottom orientation for the rail slot and limiter. (both rails where limiter is)
Instruction have top orientation for the rail slot and limiter. (both rails where limiter is)

Fix:
I didnt see any info on insertions nuts for those limiter switches. (both rails)
Didnt see any info on rail orientation for future insertions nuts for those limiter switches.

**Comment by roguenroll** [comment]
The rail Orientation is addressed briefly below. But I think it could be a lot more clear. Doing this for the first time its a bit unclear. Add a clear picture of the slot you mention. Also after some confusion on my part I notice there is post assembly insertion nuts, you might just combine the rail Orientation and slide in pre assembly nuts right then, it would make the rail Orientation more clear.

Step 4 Gantry Page
2. Attach the Second Piece of Makerslide

&

Step 5 Y-Axis
1. Attach End Plates to Makerslide

**Comment by roguenroll** [comment]
the CAD model and the instructions are opposite.

one top orientation , other bottom orientation.
