### ISSUE TITLE
X-Carve Upgrade Edits 

### ISSUE THREAD

**Issue by giovannadf** [inventables/x-carve-instructions#208]
Customer comment: I would recommend that the upgrade instructions would include or mention when doing the stiffener/ z-axis upgrade install, to change the x-axis idlers at that time since the gantry is removed. I didn't realize this and when I moved on to the belt upgrade and came to that point I said "Oh no I'm not doing that again". I was able to change the idlers with the gantry inplace, upgrade complete. 

Giovanna's recommendations: 
- Tools needed-- 3mm allen key, 8mm wrench, 4mm allen key
- Remove Bits before assembly
- material to support gantry
- Call out screws for risers earlier (move diagram)
- Call out dust shoe bracket earlier 
-call out t-slot nuts for older machines

**Comment by JulieInventables** [comment]
These changes are live
