### ISSUE TITLE
Translating the instructions to different languages

### ISSUE THREAD

**Issue by ZachKaplan** [inventables/x-carve-instructions#22]
We had a customer ask if we could translate the instructions to Spanish.  I found that Google Translate offers this service but you need to add this code snipped to each page you want translated.

``` html
<div id="google_translate_element"></div>
<script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script>
<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
```

**Comment by paulkaplan** [comment]
I thought google translate automatically offered to do that when using chrome?

**Comment by ZachKaplan** [comment]
According to their instructions only if you add the code snippet.

On Tuesday, June 23, 2015, Paul Kaplan notifications@github.com wrote:

> I thought google translate automatically offered to do that when using
> chrome?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/inventables/x-carve-instructions/issues/22#issuecomment-114592640
> .

## 

Zach Kaplan
CEO

Inventables
600 W. Van Buren #602
Chicago, IL 60607

o 312.775.7009
m 773.936.4975
f 413.332.0054

w inventables.com
t http://twitter.com/inventables

The Hardware Store for Designers - Igniting the Digital Manufacturing
Revolution
