### ISSUE TITLE
Spindle mount step doesn't make alternatives clear

### ISSUE THREAD

**Issue by paulkaplan** [inventables/x-carve-instructions#25]
The spindle mount step goes directly into the 24v spindle option without mentioning that there are 2 other possible spindle mounts. Can we use the collapsable accordion to make this difference more clear? Or at least a table of contents?

This is the step I'm referring to: http://x-carve-instructions.inventables.com/step12/

**Comment by chrisbalin** [comment]
The subnav on the right serves as a table of contents. I added a note to make it more clear.
![screen shot 2015-06-23 at 11 48 38 am](https://cloud.githubusercontent.com/assets/4512685/8311742/de6c7830-199d-11e5-954d-b9ddb7c347f2.png)

Do you think this resolves this issue?

**Comment by tleswing** [comment]
I don't think there shouldn't be a default. I think the whole thing should
accordion.

On Tue, Jun 23, 2015 at 11:49 AM, Chris Balin notifications@github.com
wrote:

> The subnav on the right serves as a table of contents. I added a note to
> make it more clear.
> [image: screen shot 2015-06-23 at 11 48 38 am]
> https://cloud.githubusercontent.com/assets/4512685/8311742/de6c7830-199d-11e5-954d-b9ddb7c347f2.png
> 
> Do you think this resolves this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/inventables/x-carve-instructions/issues/25#issuecomment-114568835
> .

## 

Tait Leswing

Project Experience Manager

Inventables

600 W. Van Buren #602

Chicago, IL 60607

o 312.775.7009

m  414.943.3343

f   413.332.0054

w  inventables.com   http://inventables.com/

t    http://twitter.com/inventables

The Hardware Store for Designers - Igniting the Digital Manufacturing
Revolution http://www.youtube.com/watch?v=fiUEC_TQJ-Q
YouTube - Videos from this email

**Comment by paulkaplan** [comment]
I think if you have to "point" to the table of contents, it is in the wrong place.

**Comment by chrisbalin** [comment]
Yeah I will make them into accordions like @tleswing suggested.

**Comment by chrisbalin** [comment]
Can I mark this resolved now? This is what the page looks like now:
![screen shot 2015-06-24 at 2 40 32 pm](https://cloud.githubusercontent.com/assets/4512685/8339703/08a62f42-1a7f-11e5-94b6-51af035b665a.png)

**Comment by tleswing** [comment]
Looks great

On Wed, Jun 24, 2015 at 2:41 PM, Paul Kaplan notifications@github.com
wrote:

> Closed #25 https://github.com/inventables/x-carve-instructions/issues/25
> .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/inventables/x-carve-instructions/issues/25#event-339318529
> .

## 

Tait Leswing

Project Experience Manager

Inventables

600 W. Van Buren #602

Chicago, IL 60607

o 312.775.7009

m  414.943.3343

f   413.332.0054

w  inventables.com   http://inventables.com/

t    http://twitter.com/inventables

The Hardware Store for Designers - Igniting the Digital Manufacturing
Revolution http://www.youtube.com/watch?v=fiUEC_TQJ-Q
YouTube - Videos from this email
