### ISSUE TITLE
Rear X Gantry rail instructions could use more detail

### ISSUE THREAD

**Issue by bonedaddy-p7** [inventables/x-carve-instructions#27]
The instructions currently state 

> Drive these screws until they are flush with the plate and then back them off a full turn.

when attaching the rearward X Gantry makerslide, but there is no mention of tightening them fully in the instructions. If these do not need fully tightened, this should be noted, or if they do need fully tightened verbage needs added on how to properly position the makerslide and the documentation should say when this is to be done

**Comment by paulkaplan** [comment]
Good point! @johndudleyhayes wanna take this one?

**Comment by HeikoH** [comment]
So what is it, do they need to be tightened? And if so, at which step?
