### ISSUE TITLE
No context for steps

### ISSUE THREAD

**Issue by nevernormal1** [inventables/x-carve-instructions#3]
The instructions have you "go in blind." They don't provide context for what you're about to do, how it fits into the overall assembly. There is no introduction to the components of the machine, the orientation (front/back, left/right), the axes, etc. We don't explain why you need to cut x feet of cable, where it's going to go, etc.

**Comment by paulkaplan** [comment]
Do you think this is still true? If so, could you post the specific sections you think this applies to?
