### ISSUE TITLE
Limit Switch Photos

### ISSUE THREAD

**Issue by burnbabybyrne** [inventables/x-carve-instructions#38]
The photos on the limit switches show conflicting wiring connections. The photo at the top of the section shows the black wires connected to the NC end of the limit switch and not to the C end. The instructions make it clear to solder the black wires to the C connector at the pivot end of the switch, whereas the photo at the top of the section shows the black wire soldered to the connector at the roller ball end of the limit switch.

**Comment by johndudleyhayes** [comment]
Thanks for pointing this out.  Should now be fixed.
