### ISSUE TITLE
X-Controller front panel screw correction

### ISSUE THREAD

**Issue by sprior** [inventables/x-carve-instructions#42]
In the "Install Front Panel" section subsection 3 "Attach Buttons And USB Cable" the instructions state "Using the M3 phillips head screws, attach the USB cable to the front panel.".  These phillips would be the ones that came preinstalled on the USB cable.  However the pictures show 2 of the Button Head Cap M3 x 6mm Screws being used.  I'm sure this is only so the screws will all match on the front panel, either will work, but the text should be changed because if the user does use the phillips screws only 8 of the 10 Button Head Cap M2 screws will be used and the 2 unaccounted screws will be confusing.

**Comment by johndudleyhayes** [comment]
Thanks for pointing this out.  The instructions have been updated.
