### ISSUE TITLE
X-Controller Usage link to "Install Controller Board" does not work

### ISSUE THREAD

**Issue by rpanier** [inventables/x-carve-instructions#43]
The link to [Install Controller Board](http://localhost:4000/x-controller/#install-controller-board) does not work.

**Comment by johndudleyhayes** [comment]
Are you referring to the link on the side bar navigation?

This worked for me:
http://x-carve-instructions.inventables.com/x-controller/#install-controller-board

Let me know if it's still broken and I'll have one of our developers take a look.

Thanks!
