### ISSUE TITLE
Broken usage link

### ISSUE THREAD

**Issue by razeh** [inventables/x-carve-instructions#51]
On this page: http://x-carve-instructions.inventables.com/upgrade/step3/1assembly/
The link to usage is: http://x-carve-instructions.inventables.com/x-controller/usage/

Which leads to a 404

**Comment by griffindennis** [comment]
This has been corrected and now points to http://x-carve-instructions.inventables.com/upgrade/step3/2usage/ . Thanks, -Griffin.
