### ISSUE TITLE
Home switches are upside-down in diagrams

### ISSUE THREAD

**Issue by joeloyj** [inventables/x-carve-instructions#52]
The orientations of the home switches in the following two diagrams don't match the photos and instructions. The 500mm and 750mm instructions have the same error.

https://github.com/inventables/x-carve-instructions/blob/4f3b9ca2341d3d69b8e355ca020bc210f4393a7a/1000mm/step2a/7homeswitch/homeswitch1.jpg

https://github.com/inventables/x-carve-instructions/blob/12f9fe5225d27766bfb51e5e76f0e4432127c364/1000mm/step2b/7homeswitch/homeswitch.jpg

**Comment by johndudleyhayes** [comment]
corrected gantry side plate diagrams
commit e444612

**Comment by johndudleyhayes** [comment]
correct x-carriage diagrams
commit 7399e00
