### ISSUE TITLE
Homeswitch diagram showing wrong attachment location

### ISSUE THREAD

**Issue by gever** [inventables/x-carve-instructions#54]
This  diagram, x-carve-instructions/1000mm/step2b/7homeswitch/homeswitch.jpg is showing the switch being attached mid-plate on the wrong side of the carriage, nowhere near the edge where it should be.

**Comment by johndudleyhayes** [comment]
To provide context when building this diagram, the viewport was not changed.  The positioning is correct, as all views were taken from a 3D model with certain portions simply hidden/revealed, however it's difficult to represent this component as it's actually being connected from behind, but viewed through a ghosted X-Carriage.  "Guidelines" were added in an attempt to show the plane at which components are being installed.  Any feedback you could provide to make this more clear would be greatly appreciated.
