### ISSUE TITLE
Step 2C Diagram Erroneously Shows Washers

### ISSUE THREAD

**Issue by gever** [inventables/x-carve-instructions#55]
This diagram:
.../1000mm/step2c/06adjustablevwheels/adjustablevwheels3.jpg

is wrong because it shows washers between the nut and the plate.

**Comment by griffindennis** [comment]
The diagram was actually not erroneous- the images and bill of materials for this step were incorrect. This has been fixed on all three sizes. Thank you for your feedback. Thanks, -Griffin.
