### ISSUE TITLE
Build instructions do not address power for router

### ISSUE THREAD

**Issue by cfinke** [inventables/x-carve-instructions#63]
I chose the Dewalt 611 router for my 1000mm X-Carve, and the build instructions do not mention how it should be powered. My assumption is that I need to control it manually, even though the Easel setup seemed to imply that the X-Controller could take care of that (maybe for a different router?).

If this is the case, then just a simple "Plug in the router" in the build instructions could clarify this.

**Comment by griffindennis** [comment]
I have included a note on this in step 5
