### ISSUE TITLE
Extra terminal block plug not mentioned

### ISSUE THREAD

**Issue by cfinke** [inventables/x-carve-instructions#64]
When I finished setting up my X-Carve, the rightmost terminal block plug on the bottom row (the one with references to the spindle) was still unused. My guess is that it can be used with certain routers, but I am using the Dewalt 611 and had no more wires to wire into it.

Everything still works, so my assumption is that I didn't miss a step, but it would be good if that terminal could be addressed. "The remaining terminal block plug is only used with routers X, Y, and Z."

**Comment by johndudleyhayes** [comment]
commit db7c46b
