### ISSUE TITLE
Z-Probe/X-Controller connection not mentioned

### ISSUE THREAD

**Issue by cfinke** [inventables/x-carve-instructions#65]
For folks who bought the optional Z-probe, the instructions never mention wiring it to the X-Controller.  I wired the red wire into the "Probe" terminal and the black wire into the remaining "GND" terminal, so I hope that was right. :-)

**Comment by griffindennis** [comment]
fixed this in 5f0ba99bb349cbfb2596da82930c8d946c6e4398
