### ISSUE TITLE
LINUX driver

### ISSUE THREAD

**Issue by Gotgot59** [inventables/x-carve-instructions#71]
Hi, I'm on linux OS.
I want to can use my carving  machine with your product.
Do you have plan to develop Linux Driver?

**Comment by griffindennis** [comment]
Hello, sorry for not addressing this sooner. Generally it's best to contact us through our support center regarding these matters. Unfortunately we don't have any plans to develop a Linux Driver at the moment. You can still export g-code by going to 'Machine->Advanced' in Easel and run it through [Universal GCode Sender](https://github.com/winder/Universal-G-Code-Sender) v1.0.9 which will take care of the actual connection to the machine.
