### ISSUE TITLE
Dust Control Instructions and Homing Switches

### ISSUE THREAD

**Issue by bible9230** [inventables/x-carve-instructions#91]
The dust control instructions need to mention a homing switch relocation.  There is a good chance that their existing homing switch location will allow the dust control shoe and brackets to collide with the y axis end plate.  

The location should be about 1" from the Y plate and 2" from the X plate.
![20171012_170214_resized](https://user-images.githubusercontent.com/23289293/31524599-a0001d58-af6f-11e7-8c0f-f4dacbeea6cd.jpg)

![20171012_170223_resized](https://user-images.githubusercontent.com/23289293/31524601-a629c7f6-af6f-11e7-9838-ab60421dcf7d.jpg)

**Comment by griffindennis** [comment]
Good call, This is definitely something that needs to be changed. This will be taken care of when integrating the dust shoe instructions themselves.

**Comment by griffindennis** [comment]
Added note on this in d4aab767260e1662aa4888a3546c2118b8e35bb6
