### ISSUE TITLE
Drag chain bracket disappear when assembling gantry?

### ISSUE THREAD

**Issue by Sidchou** [inventables/x-carve-instructions#95]
Drag chain bracket was attached to left plate in previous steps but not gantry assemble step??

**Comment by onlinelaser** [comment]
+1 Not a big deal, but it made me stumble at this step as well - I thought I must have done something wrong and flicked back and forth through the instructions until I realised it must just have been a wrong photo - a comment under the photo like "drag chain bracket not shown" would have saved some confusion
