### ISSUE TITLE
1000mm Work Area: Belting

### ISSUE THREAD

**Issue by Sidchou** [inventables/x-carve-instructions#96]
the instruction only say that i need 9 button head screw(M5x8 6, M5x25 3) but we need 12 for 6 end of belts

**Comment by johndudleyhayes** [comment]
Thanks for your feedback.  This section definitely needs some work, but should only require the 9 screws you mention and that are pictured in the first image of this step:

![](http://x-carve-instructions.inventables.com/1000mm/step4/photo/jpfs_DSC2791.jpg)

The machine was designed to only use one tensioning screw (M5x25) per length of belting.
